export const GET_PANELLIST = 'GET_PANELLIST';

export const GET_TODOLIST = 'GET_TODOLIST';

export const ADD_TODOITEM = 'ADD_TODOITEM';

export const GET_INPUTVALUE = 'GET_INPUTVALUE';

export const SET_INPUTVALUE = 'SET_INPUTVALUE';

export const SET_CHECKED = 'SET_CHECKED';

export const REMOVE_TODOITEM = 'REMOVE_TODOITEM';

export const TOGGLE_TODOLIST = 'TOGGLE_TODOLIST';
