export const START_SONG = "START_SONG";

export const SET_PLAY_MODE = "SET_PLAY_MODE";

export const SET_PLAY_LIST_SHOW = "SET_PLAY_LIST_SHOW";

export const SET_PLAYER_SHOW = "SET_PLAYER_SHOW";

export const SET_PLAY_LIST = "SET_PLAY_LIST";

export const CLEAR_PLAY_LIST = "CLEAR_PLAY_LIST";

export const SET_CURRENT_SONG = "SET_CURRENT_SONG";

export const SET_CURRENT_TIME = "SET_CURRENT_TIME";

export const SET_PLAYING_STATE = "SET_PLAYING_STATE";

export const ADD_TO_PLAY_LIST = "ADD_TO_PLAY_LIST";
